host: "0.0.0.0"
port: "3306"
user: "root"
pwd: ""

#if set to 'true' all Operators can bypass the build restriction on claimed chunks
#if set to 'false' all Operators lose access to building on other chunks and they cant unclaim them as well
opbypass: true

#if set to 'false' the owner of the chunk will not get notified if his chunk get unclaimed by an Administrator.
notifyunclaim: true

#IMPORTANT: this feature REQUIRES the plugin 'ecofy' from sirswiperlpp
chunkrent:
  paychunks: true
  #this option defines how often a player needs to pay
  #example: 1 = every minecraft day. 2 = every second minecraft day and so on
  paypercycle: 1
  moneyperchunk: 100