#MySQL login
host: "0.0.0.0"
port: "3306"
user: "root"
pwd: ""

#if set to 'true' the plugin will request the 'SirAPI' server with your key. just so I can register UUIDs, names and bans
#u can set it to 'false' any time, and it will not change how the plugin works.
#
#In case ur asking your self 'but why the key' it is so no one else can request the server with just for fun the key is generated one-time
#for more questions visit the Community discord 'http://discord.realityrift.de'
#
#This feature will be developed soon.
requestDeveloperServer: false
apikey: ""

#if set to 'true' the plugin will request the PluginUpdate Server and if anything changed it will notify u about an update.
#u can set this feature to 'false' and it will not change how the plugin works.
#
#This feature will be developed soon.
requestUpdateServer: false

#if set to 'true' all Operators can bypass the build restriction on claimed chunks
#if set to 'false' all Operators lose access to building on other chunks and they cant unclaim them as well
opbypass: true

#IMPORTANT: u should set it to 'true' if pistons are activ they can push block into untrusted Chunks.
disable-pistons: true

#this option only disables the Damage on blocks in every chunks of every world. it stil makes damage to players.
disable-crystal: true

#This option disables Respawn Anchors.
disable-anchor: true

#This option prevents that TNT Minecarts explode.
disable-tntminecarfs: true

#IMPORTANT: u should leave it to 'false' waterflows trough chunks and i am to dump to fix it ;-;
waterflows: false

#if set to 'false' the owner of the chunk will not get notified if his chunk get unclaimed by an Administrator.
notifyunclaim: true

#IMPORTANT: this feature REQUIRES the plugin 'ecofy' from sirswiperlpp
chunkrent:
  paychunks: true
  moneyperchunk: 100
  #the standart checks at 5pm(17:00)
  #the times u can select are '1am, 2am, 3am, 4am, 5am, 6am, 7am, 1pm, 2pm, 3pm, 5pm'
  checks: "5pm"

#The TimeServer is use to KeepTrack of the Time IRL so the ChunkPlugin can Pull money
#Of player banks for the chunks they claimed.
TimeServer:
  #The Official Servers are Always Correct but if u want to Code ur own u can. just keep in Mind that the serverAddress needs to be a URL of a website
  #for exapmle i used for the Official Servers 'flask' with Python. if u dont want to use this u can Recode everything here if u want. its OpenSource
  #
  #NOTE: if the OfficialServers are Offline for some reason u will be fallbacked to MicrosoftsTimeServers or GoogleTimeServers
  #if u dont want that to happen use ur own or toggle the option 'useFallbackServer'
  #
  #https://github.com/SirSwiperlpp/Chunky
  onlyOfficialServer: true

  #Currently i only Implementet the EU(Europe) and PT(Pacific Time)
  TimeZone: "EU"

  #this will Reroute to Microsoft or Google TimeServer if ur current is offline
  #set to 'false' if u want to deactivate this feature
  useFallback: true

  #the Standart is checking every 4 seconds what time it is.
  checkInterval: 4

  #Keep this like it is if the option 'onlyOfficialServer' is set to 'true'
  serverAddress: "api.realityrift.de:45655/api/tserver"

  #this is the Route that the server cheks the current server status. keep it like this if u use official servers
  statusAddress: "status.realityrift.de45654/status"

  #enable or disable commands.
  #EXAMPLE: claim: true = '/chunk claim' is activated
enabledCommands:
  claim: true
  trust: true
  info: true
  unclaim: true
  flag: true
  settype: true
  lock: true