#MySQL login
host: "0.0.0.0"
port: "3306"
user: "root"
pwd: ""

#if set to 'true' the plugin will request the 'SirAPI' server with your key. just so I can register UUIDs, names and bans
#u can set it to 'false' any time, and it will not change how the plugin works.
#
#In case ur asking your self 'but why the key' it is so no one else can request the server with just for fun the key is generated one-time
#for more questions visit the Community discord 'http://discord.realityrift.de'
#
#This feature will be developed soon.
requestDeveloperServer: false
apikey: ""

#if set to 'true' the plugin will request the PluginUpdate Server and if anything changed it will notify u about an update.
#u can set this feature to 'false' and it will not change how the plugin works.
#
#This feature will be developed soon.
requestUpdateServer: false

#if set to 'true' all Operators can bypass the build restriction on claimed chunks
#if set to 'false' all Operators lose access to building on other chunks and they cant unclaim them as well
opbypass: true

#IMPORTANT: u should set it to 'true' if pistons are activ they can push block into untrusted Chunks.
disable-pistons: true

#this option only disables the Damage on blocks in every chunks of every world. it stil makes damage to players.
disable-crystal: true

#This option disables Respawn Anchors.
disable-anchor: true

#This option prevents that TNT Minecarts explode.
disable-tntminecarfs: true

#IMPORTANT: u should leave it to 'false' waterflows trough chunks and i am to dump to fix it ;-;
waterflows: false

#if set to 'false' the owner of the chunk will not get notified if his chunk get unclaimed by an Administrator.
notifyunclaim: true

#IMPORTANT: this feature REQUIRES the plugin 'ecofy' from sirswiperlpp
chunkrent:
  paychunks: true
  moneyperchunk: 100
  #the standart checks at 17:00
  #IMPORTANT: u need to give the time in this format: HH:mm
  checks: "17:00"

#The TimeServer is use to KeepTrack of the Time IRL so the ChunkPlugin can Pull money
#Of player banks for the chunks they claimed.
TimeServer:
  #Just put in ur TimeZone.
  #
  #If u dont know ur timezone go to this link: https://www.timezoneconverter.com/cgi-bin/findzone/findzone
  TimeZone: "Europe/Berlin"

  #enable or disable commands.
  #EXAMPLE: claim: true = '/chunk claim' is activated
enabledCommands:
  claim: true
  trust: true
  info: true
  unclaim: true
  flag: true
  settype: true
  lock: true