name: Chunky
authors:
  - SirSwiperlpp
  - Crasher508
version: '${project.version}'
main: de.realityrift.chunky.Main.Main
api-version: '1.20'

commands:
  chunk:
    permission: chunk.command
    tab-completer: de.realityrift.chunky.TabCompletter.ChunkTab

permissions:
  chunk.command:
    default: true
